# Generated by Django 5.1.5 on 2025-01-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mavan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
    ]
